;;; company-go-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-go.el

(autoload 'company-go "company-go" "\


(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-go" '("company-go-"))

;;; End of scraped data

(provide 'company-go-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-go-autoloads.el ends here
